#!/usr/bin/env tsx
/**
 * extract-git-history.ts — Build a replay corpus from vcode's own git commits.
 *
 * Rationale: every accepted commit is ground truth. The commit message is the
 * "user intent" a developer had; the resulting diff is what succeeded. A model
 * that, given the pre-commit state and the commit message, can produce a diff
 * that typechecks (and ideally matches the actual commit) is demonstrating real
 * coding competence on YOUR specific codebase — not on generic Exercism problems.
 *
 * This complements benchmarks/exercises-aider/ (generic benchmark) with
 * repo-specific ground truth. A model that scores well here is adapted to
 * vcode's style, conventions, and tooling.
 *
 * Output: benchmarks/git-corpus/commits.jsonl. Each record:
 *   {
 *     commit_hash: string,           // the commit whose behavior we replicate
 *     parent_hash: string,           // checkout point for the replay
 *     message: string,               // commit subject + body (= user prompt)
 *     files_changed: string[],       // paths the model is allowed to edit
 *     files_to_check: string[],      // subset that should typecheck after edits
 *     stats: { additions, deletions, files },
 *     committed_at: string,
 *   }
 *
 * Filtering heuristic — keep only commits likely to be good test samples:
 *   - Touches ≤ 4 source files (ignores dist/, node_modules/, etc.)
 *   - Not a merge commit
 *   - Commit message ≥ 20 chars and not auto-generated ("bump version", etc.)
 *   - Touches files under src/ or scripts/ (code changes, not pure docs)
 *
 * Usage:
 *   npx tsx scripts/extract-git-history.ts [--limit 40] [--since 3.months] [--max-files 4]
 */

import { execFileSync } from 'child_process';
import { writeFile, mkdir } from 'fs/promises';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { parseArgs } from 'util';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '..');
const OUT_DIR = resolve(REPO_ROOT, 'benchmarks', 'git-corpus');
const OUT_PATH = resolve(OUT_DIR, 'commits.jsonl');

const { values } = parseArgs({
  options: {
    limit: { type: 'string', default: '40' },
    since: { type: 'string', default: '6.months' },
    'max-files': { type: 'string', default: '4' },
  },
  strict: false,
});

const LIMIT = parseInt(values.limit as string, 10);
const SINCE = values.since as string;
const MAX_FILES = parseInt(values['max-files'] as string, 10);

function git(...args: string[]): string {
  return execFileSync('git', args, { cwd: REPO_ROOT, encoding: 'utf-8', maxBuffer: 50 * 1024 * 1024 }).trimEnd();
}

interface CommitRecord {
  commit_hash: string;
  parent_hash: string;
  message: string;
  files_changed: string[];
  files_to_check: string[];
  stats: { additions: number; deletions: number; files: number };
  committed_at: string;
}

const AUTO_GENERATED_PATTERNS = [
  /^bump version/i,
  /^chore\(release\)/i,
  /^update dependencies?/i,
  /^upgrade deps?/i,
  /^npm audit fix/i,
  /^wip[: ]/i,
  /^merge /i,
  /^revert /i,
];

function looksAutoGenerated(subject: string): boolean {
  return AUTO_GENERATED_PATTERNS.some(p => p.test(subject));
}

function shouldKeepFile(path: string): boolean {
  // Source-code-like paths under src/ or scripts/ in TypeScript/JavaScript.
  // Ignore builds, lockfiles, docs-only, tests-only.
  if (!path.match(/\.(ts|tsx|js|mjs|cjs)$/)) return false;
  if (path.startsWith('dist/')) return false;
  if (path.startsWith('node_modules/')) return false;
  if (path.match(/\.test\.(ts|tsx|js)$/)) return false;  // test files alone aren't a "feature"
  return path.startsWith('src/') || path.startsWith('scripts/');
}

function getCommits(): string[] {
  // Most recent first, skip merges, commit hashes only.
  const out = git('log', '--no-merges', `--since=${SINCE}`, '--format=%H');
  return out.split('\n').filter(Boolean);
}

function commitDetails(hash: string): CommitRecord | null {
  const parent = git('log', '-1', '--format=%P', hash).split(' ')[0];
  if (!parent) return null;  // initial commit has no parent, skip

  const subject = git('log', '-1', '--format=%s', hash);
  const body = git('log', '-1', '--format=%b', hash);
  const committed = git('log', '-1', '--format=%cI', hash);

  if (subject.length < 20 || looksAutoGenerated(subject)) return null;

  // Files touched by this commit
  const files = git('show', '--name-only', '--format=', hash)
    .split('\n')
    .filter(Boolean);

  if (files.length === 0 || files.length > MAX_FILES * 2) return null;

  const sourceFiles = files.filter(shouldKeepFile);
  if (sourceFiles.length === 0 || sourceFiles.length > MAX_FILES) return null;

  // numstat: per-file additions/deletions
  const numstat = git('show', '--numstat', '--format=', hash)
    .split('\n')
    .filter(Boolean)
    .map(l => l.split('\t'));
  const stats = numstat.reduce(
    (acc, [a, d]) => ({
      additions: acc.additions + (parseInt(a, 10) || 0),
      deletions: acc.deletions + (parseInt(d, 10) || 0),
      files: acc.files + 1,
    }),
    { additions: 0, deletions: 0, files: 0 }
  );

  // Reject trivially small or impossibly large commits
  if (stats.additions + stats.deletions < 5) return null;
  if (stats.additions + stats.deletions > 600) return null;

  const message = body.trim() ? `${subject}\n\n${body.trim()}` : subject;

  return {
    commit_hash: hash,
    parent_hash: parent,
    message,
    files_changed: files,
    files_to_check: sourceFiles,
    stats,
    committed_at: committed,
  };
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });

  const hashes = getCommits();
  console.log(`Scanning ${hashes.length} commits since ${SINCE}...`);

  const records: CommitRecord[] = [];
  for (const h of hashes) {
    if (records.length >= LIMIT) break;
    const rec = commitDetails(h);
    if (rec) records.push(rec);
  }

  const lines = records.map(r => JSON.stringify(r)).join('\n') + '\n';
  await writeFile(OUT_PATH, lines);

  console.log(`\nWrote ${records.length} commit samples → ${OUT_PATH}`);
  if (records.length > 0) {
    console.log(`\nFirst sample preview:`);
    const r = records[0];
    console.log(`  ${r.commit_hash.slice(0, 10)}  ${r.message.split('\n')[0].slice(0, 70)}`);
    console.log(`  Files: ${r.files_to_check.join(', ')}`);
    console.log(`  Stats: +${r.stats.additions} -${r.stats.deletions}`);
  }
  console.log(`\nNext: npx tsx scripts/replay-git-history.ts --candidate <model>`);
}

main().catch(e => { console.error(e); process.exit(1); });
